-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
    -   id: autopep8
        files: \.py$

-   repo: https://github.com/pre-commit/mirrors-black
    rev: v22.3.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.9.0
    hooks:
    -   id: mypy
        files: \.py$
        args: ['--ignore-missing-imports']

-   repo: https://github.com/pre-commit/mirrors-flake8
    rev: v3.9.2
    hooks:
    -   id: flake8
        files: \.py$
        args: ['--max-line-length=88']

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.13.0
    hooks:
    -   id: pylint
        files: \.py$
        args: ['--max-line-length=88']
